# Generated by Django 4.2.6 on 2024-01-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
