# Generated by Django 4.2.6 on 2023-10-23 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garage', models.IntegerField(default=0)),
                ('sqft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pic', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('pic_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('pic_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('pic_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('pic_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('pic_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
